### ISSUE TITLE
Feature request: Add passthrough for kubeconfig and context flags

### ISSUE THREAD

**Issue by deiga** [thecloudnatives/krew-prune#5]
This will allow people with multiple clusters to more easily use these plugins

**Comment by etiennetremel** [comment]
context flag is now supported, thanks to @bitfisher : https://github.com/FikaWorks/kubectl-plugins/pull/11

**Comment by etiennetremel** [comment]
Should be usable after upgrading your local Krew index: 
```
$ kubectl krew upgrade
```

https://github.com/kubernetes-sigs/krew-index/pull/1845
