### ISSUE TITLE
Feature request: Allow passing multiple cronjobs

### ISSUE THREAD

**Issue by austince** [thecloudnatives/krew-prune#6]
Hey, thanks for the great tool. I'm wondering how difficult it would be to support passing multiple cronjobs to exec, so we could use the plugin like: 

```sh
kubectl exec-cronjob some-cj-{a,b,c}
```

Thanks again!

**Comment by moredhel** [comment]
Hi @austince,

thanks for the bug report. Kubernetes has merged this functionality into core, we would recommend using that now. https://github.com/FikaWorks/kubectl-plugins/pull/10/.

You can refer to the docs here: https://kubernetes.io/docs/reference/generated/kubectl/kubectl-commands#-em-job-em-
